version: 2

jobs:
  shellcheck:
    machine:
      - image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            echo "starting"
            perl checkpatch.pl

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
