version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            perl checkpatch.pl

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
